version: '3'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - "DATABASE_URL=restbench"
      - "POSTGRES_DATABASE=restbench"
      - "POSTGRES_USER=restbench"
      - "POSTGRES_PASSWORD=restbench"
    volumes:
      - db-data:/var/lib/postgresql/data
      - .initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restbench"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
